# shellcheck shell=bash
# aliases.zsh - GENERATED by gen-aliases.sh from manifest.yaml. Do not hand-edit.
# Sourced from ic-workflow.zsh (dotfiles-nix), which itself only loads in
# interactive shells; the guard below makes this file a no-op everywhere else.
[[ -o interactive ]] || return 0

FLEET_ROOT="$HOME/github"
FLEET_DIR="$FLEET_ROOT/.fleet"

# --- per-repo aliases (jump + run) ---
alias cdlav='cd $HOME/github/lavish-axi'
command -v lavish-axi >/dev/null && alias lav=lavish-axi
alias cdfm='cd $HOME/github/firstmate'
alias cdnm='cd $HOME/github/no-mistakes'
command -v no-mistakes >/dev/null && alias nm=no-mistakes
alias cdaxi='cd $HOME/github/axi'
alias cdcda='cd $HOME/github/chrome-devtools-axi'
command -v chrome-devtools-axi >/dev/null && alias cda=chrome-devtools-axi
alias cdgha='cd $HOME/github/gh-axi'
command -v gh-axi >/dev/null && alias gha=gh-axi
alias cdap='cd $HOME/github/autopreso'
command -v autopreso >/dev/null && alias ap=autopreso
alias cdbm='cd $HOME/github/baby-menu'
alias cdta='cd $HOME/github/tasks-axi'
command -v tasks-axi >/dev/null && alias ta=tasks-axi
alias cdqa='cd $HOME/github/quota-axi'
command -v quota-axi >/dev/null && alias qa=quota-axi
alias cdth='cd $HOME/github/treehouse'
command -v treehouse >/dev/null && alias th=treehouse
alias cdsp='cd $HOME/github/short-pipe'
alias cdtbc='cd $HOME/github/trial-by-combat'
alias cdjr='cd $HOME/github/justroll'
command -v justroll >/dev/null && alias jr=justroll
alias cdpz='cd $HOME/github/presize'
alias cdob='cd $HOME/github/org-bench'
alias cdsb='cd $HOME/github/superpowers-bench'
alias cdpb='cd $HOME/github/programbench-bench'
alias cddot='cd $HOME/github/dotfiles-nix'
alias cdgnhf='cd $HOME/github/gnhf'
command -v gnhf >/dev/null && alias gn=gnhf
alias cdwh='cd $HOME/github/wheelhouse'

# --- fleet commands ---
alias fleet-sync='sync-forks'
alias fleet-sync-dry='sync-forks --dry-run'
alias fleet-doctor='$FLEET_DIR/doctor.sh'

# One-line git status for every fleet repo.
fleet-status() {
  local r d branch dirty marker
  while IFS= read -r r; do
    d="$FLEET_ROOT/$r"
    [ -d "$d/.git" ] || { printf '%-22s MISSING\n' "$r"; continue; }
    branch=$(git -C "$d" symbolic-ref --short HEAD 2>/dev/null || echo DETACHED)
    dirty=$(git -C "$d" status --porcelain 2>/dev/null | wc -l | tr -d ' ')
    marker=clean; [ "$dirty" != 0 ] && marker="dirty($dirty)"
    printf '%-22s %-12s %s\n' "$r" "$branch" "$marker"
  done < <(awk '/^- name:/ {print $3}' "$FLEET_DIR/manifest.yaml")
}

# Fuzzy jump to a fleet repo (falls back to a plain menu without fzf).
fleet-cd() {
  local r
  if command -v fzf >/dev/null; then
    r=$(awk '/^- name:/ {print $3}' "$FLEET_DIR/manifest.yaml" | fzf --prompt='fleet> ') || return
  else
    select r in $(awk '/^- name:/ {print $3}' "$FLEET_DIR/manifest.yaml"); do break; done
  fi
  [ -n "$r" ] || return 1
  cd "$FLEET_ROOT/$r" || return
}
