#!/usr/bin/env bash
# gen-aliases.sh: regenerate aliases.zsh from manifest.yaml.
# aliases.zsh is generated output - never hand-edit it; edit the manifest's
# aliases fields and re-run this script.
set -euo pipefail

FLEET_DIR="$(cd -P -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
MANIFEST="$FLEET_DIR/manifest.yaml"
OUT="$FLEET_DIR/aliases.zsh"

[ -f "$MANIFEST" ] || { echo "manifest not found: $MANIFEST" >&2; exit 1; }

# Emit "name|path|jump|run|bin" per manifest entry (run/bin may be empty).
entries() {
  awk '
    function flush() {
      if (name != "") printf "%s|%s|%s|%s|%s\n", name, path, jump, run, bin
      name = ""; path = ""; jump = ""; run = ""; bin = ""
    }
    /^- name:/  { flush(); name = $3 }
    /^  path:/  { path = $2 }
    /^  provides_bin:/ {
      bin = $0; sub(/^  provides_bin: *\[/, "", bin); sub(/\].*/, "", bin)
      sub(/,.*/, "", bin)   # first binary is the canonical run target
    }
    /^  aliases:/ {
      if (match($0, /jump: *[A-Za-z0-9_-]+/)) { jump = substr($0, RSTART, RLENGTH); sub(/jump: */, "", jump) }
      if (match($0, /run: *[A-Za-z0-9_-]+/))  { run  = substr($0, RSTART, RLENGTH); sub(/run: */, "", run) }
    }
    END { flush() }
  ' "$MANIFEST"
}

{
  cat <<'HEADER'
# shellcheck shell=bash
# aliases.zsh - GENERATED by gen-aliases.sh from manifest.yaml. Do not hand-edit.
# Sourced from ic-workflow.zsh (dotfiles-nix), which itself only loads in
# interactive shells; the guard below makes this file a no-op everywhere else.
[[ -o interactive ]] || return 0

FLEET_ROOT="$HOME/github"
FLEET_DIR="$FLEET_ROOT/.fleet"
HEADER

  echo
  echo "# --- per-repo aliases (jump + run) ---"
  while IFS='|' read -r _ path jump run bin; do
    p="${path/#\~/\$HOME}"
    [ -n "$jump" ] && printf 'alias %s='"'"'cd %s'"'"'\n' "$jump" "$p"
    if [ -n "$run" ] && [ -n "$bin" ]; then
      printf 'command -v %s >/dev/null && alias %s=%s\n' "$bin" "$run" "$bin"
    fi
  done < <(entries)

  cat <<'FOOTER'

# --- fleet commands ---
alias fleet-sync='sync-forks'
alias fleet-sync-dry='sync-forks --dry-run'
alias fleet-doctor='$FLEET_DIR/doctor.sh'

# One-line git status for every fleet repo.
fleet-status() {
  local r d branch dirty marker
  while IFS= read -r r; do
    d="$FLEET_ROOT/$r"
    [ -d "$d/.git" ] || { printf '%-22s MISSING\n' "$r"; continue; }
    branch=$(git -C "$d" symbolic-ref --short HEAD 2>/dev/null || echo DETACHED)
    dirty=$(git -C "$d" status --porcelain 2>/dev/null | wc -l | tr -d ' ')
    marker=clean; [ "$dirty" != 0 ] && marker="dirty($dirty)"
    printf '%-22s %-12s %s\n' "$r" "$branch" "$marker"
  done < <(awk '/^- name:/ {print $3}' "$FLEET_DIR/manifest.yaml")
}

# Fuzzy jump to a fleet repo (falls back to a plain menu without fzf).
fleet-cd() {
  local r
  if command -v fzf >/dev/null; then
    r=$(awk '/^- name:/ {print $3}' "$FLEET_DIR/manifest.yaml" | fzf --prompt='fleet> ') || return
  else
    select r in $(awk '/^- name:/ {print $3}' "$FLEET_DIR/manifest.yaml"); do break; done
  fi
  [ -n "$r" ] || return 1
  cd "$FLEET_ROOT/$r" || return
}
FOOTER
} > "$OUT"

echo "wrote $OUT ($(grep -c '^alias\|^command -v' "$OUT" | tr -d ' ') alias lines)"
